apiVersion: v1
kind: Secret
metadata:
  name: doris-operator-secret-cert
  namespace: {{ template "operator.namespace" . }}
  labels:
    control-plane: {{ template "kube-doris.name" . }}-operator
    app.kubernetes.io/instance: {{ template "kube-doris.name" . }}-operator