apiVersion: v1
kind: Service
metadata:
  name: {{ include "m3e.fullname" . }}
  labels:
    {{- include "m3e.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6008
      protocol: TCP
      name: http
  selector:
    {{- include "m3e.selectorLabels" . | nindent 4 }}
