{{- if .Values.dorisCluster.authSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "doriscluster.secret.name" . }}
  namespace: {{ template "doriscluster.namespace" . }}
  labels:
    app.kubernetes.io/name: doriscluster
    app.kubernetes.io/instance: {{ template "doriscluster.name" . }}
    app.kubernetes.io/part-of: {{ template "kube-control.name" . }}
type: kubernetes.io/basic-auth
data:
  {{- toYaml .Values.dorisCluster.authSecret | nindent 2}}
{{- end }}